# Generated by Django 5.1 on 2025-02-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskOrdering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='todo.task')),
                ('second_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='todo.task')),
            ],
        ),
    ]
